name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Cachix
        uses: cachix/cachix-action@v17
        with:
          name: kopicat
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and test
        run: |
          nix-build --argstr pnpmDepsHash sha256-+qysXTGTj82hXKzWNOsTl9VArOgfWAccPb26/mYUf5s=
          sha256sum $(nix-build -A backend --no-out-link)/*.wasm
